import { StyleSheet } from 'react-native';

import { Fonts, MatchdayTheme } from '@/constants/theme';

export const authStyles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: MatchdayTheme.colors.night,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    alignItems: 'center',
    flexGrow: 1,
    paddingHorizontal: 10,
    paddingTop: 52,
    paddingBottom: 36,
  },
  panel: {
    backgroundColor: 'transparent',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  panelMobile: {
    width: '100%',
    paddingTop: 18,
  },
  contentWrap: {
    alignSelf: 'center',
    maxWidth: 420,
    width: '100%',
  },
  logoWrap: {
    alignSelf: 'center',
    backgroundColor: MatchdayTheme.colors.blue900,
    borderColor: MatchdayTheme.colors.blue700,
    borderRadius: 20,
    borderWidth: 1,
    height: 68,
    marginBottom: 28,
    paddingHorizontal: 14,
    paddingVertical: 10,
    width: 190,
  },
  logo: {
    height: '100%',
    width: '100%',
  },
  card: {
    backgroundColor: MatchdayTheme.colors.surfaceElevated,
    borderColor: 'rgba(12,74,110,0.12)',
    borderRadius: MatchdayTheme.radii.xl,
    borderWidth: 1,
    paddingHorizontal: 22,
    paddingVertical: 32,
    width: "100%",
    ...MatchdayTheme.shadows.soft,
  },
  eyebrow: {
    color: MatchdayTheme.colors.blue800,
    fontFamily: Fonts.sans,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: MatchdayTheme.colors.blue900,
    fontFamily: Fonts.display,
    fontSize: 52,
    fontWeight: '900',
    letterSpacing: 0,
    marginTop: 12,
    textTransform: 'uppercase',
  },
  subtitle: {
    color: MatchdayTheme.colors.slate700,
    fontFamily: Fonts.sans,
    fontSize: 16,
    lineHeight: 25,
    marginTop: 12,
  },
  formSection: {
    gap: 20,
    marginTop: 36,
  },
  fieldBlock: {
    gap: 8,
  },
  fieldLabel: {
    color: MatchdayTheme.colors.blue700,
    fontFamily: Fonts.sans,
    fontSize: 14,
    fontWeight: '600',
  },
  inputShell: {
    alignItems: 'center',
    backgroundColor: MatchdayTheme.colors.surface,
    borderColor: 'rgba(12,74,110,0.12)',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 58,
    paddingHorizontal: 18,
  },
  input: {
    color: MatchdayTheme.colors.blue900,
    flex: 1,
    fontFamily: Fonts.sans,
    fontSize: 15,
  },
  errorText: {
    backgroundColor: '#fff1f2',
    borderColor: '#fecdd3',
    borderRadius: 14,
    borderWidth: 1,
    color: MatchdayTheme.colors.danger,
    fontFamily: Fonts.sans,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  noticeText: {
    backgroundColor: '#ecfdf5',
    borderColor: '#bbf7d0',
    borderRadius: 14,
    borderWidth: 1,
    color: '#166534',
    fontFamily: Fonts.sans,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  checkboxRow: {
    alignItems: 'center',
    backgroundColor: MatchdayTheme.colors.surface,
    borderColor: 'rgba(12,74,110,0.12)',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  checkbox: {
    alignItems: 'center',
    backgroundColor: MatchdayTheme.colors.surfaceCard,
    borderColor: MatchdayTheme.colors.slate300,
    borderRadius: 8,
    borderWidth: 1,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  checkboxChecked: {
    backgroundColor: MatchdayTheme.colors.blue800,
    borderColor: MatchdayTheme.colors.blue800,
  },
  checkboxText: {
    color: MatchdayTheme.colors.slate700,
    flex: 1,
    fontFamily: Fonts.sans,
    fontSize: 14,
  },
  submitButton: {
    alignItems: 'center',
    backgroundColor: MatchdayTheme.colors.blue800,
    borderRadius: MatchdayTheme.radii.pill,
    justifyContent: 'center',
    minHeight: 58,
    paddingHorizontal: 18,
  },
  submitButtonDisabled: {
    opacity: 0.55,
  },
  submitButtonText: {
    color: MatchdayTheme.colors.white,
    fontFamily: Fonts.sans,
    fontSize: 15,
    fontWeight: '700',
  },
  footerText: {
    color: MatchdayTheme.colors.slate700,
    fontFamily: Fonts.sans,
    fontSize: 14,
    marginTop: 20,
    textAlign: 'center',
  },
  footerLink: {
    color: MatchdayTheme.colors.blue800,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  backLink: {
    color: MatchdayTheme.colors.blue800,
    fontFamily: Fonts.sans,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 16,
    textAlign: 'center',
  },
});
